data: {
  status: 200,
  statusText: 'OK',
  headers: Object [AxiosHeaders] {
    date: 'Mon, 02 Dec 2024 20:38:57 GMT',
    'content-type': 'application/json;charset=UTF-8',
    'transfer-encoding': 'chunked',
    connection: 'keep-alive',
    vary: 'Accept-Encoding, Accept,Accept-Encoding',
    'cache-control': 'max-age=0',
    'x-content-type-options': 'nosniff',
    'x-request-id': 'be729583-27a1-448e-8eec-97948b098ffc',
    'x-xss-protection': '1; mode=block',
    'strict-transport-security': 'max-age=16070400; includeSubDomains; preload',
    'access-control-allow-origin': '*',
    'access-control-allow-headers': 'Content-Type',
    'access-control-allow-methods': 'PUT, GET, POST, DELETE, OPTIONS',
    'access-control-max-age': '86400',
    'timing-allow-origin': '*'
  },
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      Authorization: 'Bearer APP_USR-8870352348996134-113008-2e47bfa3a451c63ed5cdb261262dab13-1622982866',
      'User-Agent': 'axios/1.7.7',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'https://api.mercadopago.com/v1/payments/94748468691',
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: true,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.mercadopago.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.mercadopago.com',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _writableState: [WritableState],
      allowHalfOpen: false,
      _maxListeners: undefined,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      timeout: 5000,
      parser: null,
      _httpMessage: null,
      autoSelectFamilyAttemptedAddresses: [Array],
      [Symbol(alpncallback)]: null,
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: -1,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 5000,
        _idlePrev: [TimersList],
        _idleNext: [Timeout],
        _idleStart: 2201869,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 250683,
        [Symbol(triggerId)]: 250681,
        [Symbol(kResourceStore)]: [Object],
        [Symbol(kResourceStore)]: [Object],
        [Symbol(kResourceStore)]: undefined,
        [Symbol(kResourceStore)]: undefined,
        [Symbol(kResourceStore)]: [Object],
        [Symbol(kResourceStore)]: undefined,
        [Symbol(kResourceStore)]: undefined,
        [Symbol(kResourceStore)]: undefined,
        [Symbol(kResourceStore)]: undefined,
        [Symbol(kResourceStore)]: undefined,
        [Symbol(kResourceStore)]: undefined,
        [Symbol(kResourceStore)]: undefined
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 1,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'GET /v1/payments/94748468691 HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Authorization: Bearer APP_USR-8870352348996134-113008-2e47bfa3a451c63ed5cdb261262dab13-1622982866\r\n' +
      'User-Agent: axios/1.7.7\r\n' +
      'Accept-Encoding: gzip, compress, deflate, br\r\n' +
      'Host: api.mercadopago.com\r\n' +
      'Connection: keep-alive\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype] {},
      freeSockets: [Object: null prototype],
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/v1/payments/94748468691',
    _ended: true,
    res: IncomingMessage {
      _events: [Object],
      _readableState: [ReadableState],
      _maxListeners: undefined,
      socket: null,
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 200,
      statusMessage: 'OK',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [Circular *1],
      _eventsCount: 4,
      responseUrl: 'https://api.mercadopago.com/v1/payments/94748468691',
      redirects: [],
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 34,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api.mercadopago.com',
    protocol: 'https:',
    _redirectable: Writable {
      _events: [Object],
      _writableState: [WritableState],
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _eventsCount: 3,
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://api.mercadopago.com/v1/payments/94748468691',
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false
    },
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      authorization: [Array],
      'user-agent': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 16384,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  data: {
    accounts_info: null,
    acquirer_reconciliation: [],
    additional_info: {
      authentication_code: null,
      available_balance: null,
      ip_address: '177.96.30.26',
      items: [Array],
      nsu_processadora: null
    },
    authorization_code: '301299',
    binary_mode: false,
    brand_id: null,
    build_version: '0.0.1-hotfix-139',
    call_for_authorize_id: null,
    captured: true,
    card: {
      bin: '50314332',
      cardholder: [Object],
      country: null,
      date_created: '2024-12-02T16:38:56.000-04:00',
      date_last_updated: '2024-12-02T16:38:56.000-04:00',
      expiration_month: 11,
      expiration_year: 2025,
      first_six_digits: '503143',
      id: null,
      last_four_digits: '6351',
      tags: []
    },
    charges_details: [ [Object] ],
    charges_execution_info: { internal_execution: [Object] },
    collector_id: 1622982866,
    corporation_id: null,
    counter_currency: null,
    coupon_amount: 0,
    currency_id: 'BRL',
    date_approved: '2024-12-02T16:38:56.000-04:00',
    date_created: '2024-12-02T16:38:56.000-04:00',
    date_last_updated: '2024-12-02T16:38:56.000-04:00',
    date_of_expiration: null,
    deduction_schema: null,
    description: 'QR Code Love',
    differential_pricing_id: null,
    external_reference: '{"hash":"4e36df30-f000-4f62-8806-7f8bc9a2b8b8","name":"test"}',
    fee_details: [ [Object] ],
    financing_group: null,
    id: 94748468691,
    installments: 1,
    integrator_id: null,
    issuer_id: '24',
    live_mode: true,
    marketplace_owner: null,
    merchant_account_id: null,
    merchant_number: null,
    metadata: {},
    money_release_date: '2024-12-02T16:38:56.000-04:00',
    money_release_schema: null,
    money_release_status: 'released',
    notification_url: 'https://0722-2804-1b2-6043-6d70-3db9-284d-f200-6896.ngrok-free.app/api/mercadopago/webhook',
    operation_type: 'regular_payment',
    order: { id: '25643454759', type: 'mercadopago' },
    payer: {
      email: 'test_user_1157297040@testuser.com',
      entity_type: null,
      first_name: null,
      id: '1621051517',
      identification: [Object],
      last_name: null,
      operator_id: null,
      phone: [Object],
      type: null
    },
    payment_method: {
      data: [Object],
      id: 'master',
      issuer_id: '24',
      type: 'credit_card'
    },
    payment_method_id: 'master',
    payment_type_id: 'credit_card',
    platform_id: null,
    point_of_interaction: {
      business_info: [Object],
      transaction_data: [Object],
      type: 'CHECKOUT'
    },
    pos_id: null,
    processing_mode: 'aggregator',
    refunds: [],
    release_info: null,
    shipping_amount: 0,
    sponsor_id: null,
    statement_descriptor: 'Mercadopago*fake',
    status: 'approved',
    status_detail: 'accredited',
    store_id: null,
    tags: null,
    taxes_amount: 0,
    transaction_amount: 19.99,
    transaction_amount_refunded: 0,
    transaction_details: {
      acquirer_reference: null,
      external_resource_url: null,
      financial_institution: null,
      installment_amount: 19.99,
      net_received_amount: 18.99,
      overpaid_amount: 0,
      payable_deferral_period: null,
      payment_method_reference_id: null,
      total_paid_amount: 19.99
    }
  }
}